### ISSUE TITLE
Readme.md missing filename

### ISSUE THREAD

**Issue by getarun** [Suthek/ShadowTeXSR5#2]
You state renaming the .mst file to be the same as FILENAME.tex, i.e.FILENAME.mst.
README.md:
`  - The index_style.mst. Rename it to <yourtexfilename>.mst.`
does not view on github which only shows
`  - The index_style.mst. Rename it to .mst.`

Maybe some markup issues involved.

**Comment by Suthek** [comment]
Indeed. I escaped the symbols, so it works now.
