### ISSUE TITLE
Unable to populate srtable with datatool

### ISSUE THREAD

**Issue by avanier** [Suthek/ShadowTeXSR5#3]
This is likely a [`datatool`][dt] problem and not a problem with `ShadowTeXSR5`... but I'm at my wits end. Halp!

[dt]: https://ctan.org/pkg/datatool?lang=en

I'm trying to populate `srtable` with data from an external file to keep my book clean, but whatever I do, the first cell of the first row of my table always has what looks like an extra line break.

If I use for example:

```latex
\usepackage{datatool}

\begin{filecontents*}{foo.csv}
a,b,c
10,20,30
40,50,60
\end{filecontents*}

\DTLloaddb{foo}{foo.csv}

\begin{blackbox}{DTL Test Table}
  \begin{srtable}{Xcc}{A & B & C}%
  \DTLforeach*{foo}{\keyA=a,\keyB=b,\keyC=c}{%
    \DTLiffirstrow{}{\\}\keyA & \keyB & \keyC} \\
  \end{srtable}
\end{blackbox}
```

I get the following result:

![screenshot-20200416-T1751-35 229668486](https://user-images.githubusercontent.com/4009658/79510217-f06e2500-800a-11ea-9f6d-73b0319d63cc.png)

No combination of `\nobreak`, `\nolinebreak` or swearing has gotten me what I want so far. I've extracted `\NewEnviron`, broke it apart, entered every line manually... and I get the same behaviour. It seems `\DTLforeach` prepends a line break that I can't get rid of.

The closest I managed to get to something that looks like aligned text is this abomination:

```latex
\usepackage{datatool}

\begin{filecontents*}{foo.csv}
a,b,c
10,20,30
40,50,60
\end{filecontents*}

\DTLloaddb{foo}{foo.csv}

\begin{blackbox}{DTL Test Table}
  \begin{srtable}{Xcc}{A & B & C}%
  ~\DTLforeach*{foo}{\keyA=a,\keyB=b,\keyC=c}{% <<<< Notice the tilde turning the break into an unbreakeable space
    \DTLiffirstrow{}{\\}\keyA & \keyB & \keyC} \\
  \end{srtable}
\end{blackbox}
```

![screenshot-20200416-T1757-14 539036164](https://user-images.githubusercontent.com/4009658/79510645-b7828000-800b-11ea-9371-f5f53c83ca39.png)

My question is the following: If I can't use `datatool` to insert external data into `srtable`, do you have another recommendation to do the same thing? Maintaining weapons tables or any data heavy reference material directly into LaTeX is rather unwieldy. :disappointed:

**Comment by avanier** [comment]
I fixed it by switching to `csvsimple`.

```latex
\usepackage{csvsimple}

\begin{filecontents*}{foo.csv}
a,b,c
10,20,30
40,50,60
\end{filecontents*}

\begin{blackbox}{DTL Test Table}
  \begin{srtable}{X c c}{A & B & C}%
    \csvreader[head to column names]{foo.csv}{}%
    {\csviffirstrow{}{\\}\a & \b & \c} \\
  \end{srtable}
\end{blackbox}
```

![screenshot-20200417-T0217-47 750601518](https://user-images.githubusercontent.com/4009658/79538094-a5c3cb80-8051-11ea-969d-7ff982e3e311.png)

**Comment by Suthek** [comment]
That's actually a pretty neat functionality. I think I'll introduce that into the core; so you can just put the header into the CSV-File as well. Thanks for bringing up the issue (and solving it).
