### ISSUE TITLE
Node with document title turns white

### ISSUE THREAD

**Issue by Netchiman** [Suthek/ShadowTeXSR5#5]
The node containing the document title on pages with a chapter header are filled white instead of red. Changing line 425 in ShadowTeXSR5.cls from:

```
\node[anchor=south west, fill=redtext, minimum height=6mm, white, font=\headerfont] at (-.5\paperwidth+15mm,.5\paperheight-14mm) {\MakeUppercase{\sr@doctitle}};
```

to:

```
\node[anchor=south west, fill=redtext, minimum height=6mm, text=white, font=\headerfont] at (-.5\paperwidth+15mm,.5\paperheight-14mm) {\MakeUppercase{\sr@doctitle}};
```

fixes the issue.

OS:  Win 7 64bit
LaTeX:  MikTeX 21.3
Editor:  TeXworks 0.6.6

**Comment by Suthek** [comment]
Fixed through proposed pull request.
83851407aa528c022348cda641ed9e6fa21cc66d
