### ISSUE TITLE
What's the copyright license on this?

### ISSUE THREAD

**Issue by Gaptoothmcgee** [Suthek/ShadowTeXSR5#8]
So I'm looking to make an adventure module in 5e as part of the Holostreets initiative, and I'd like to use this to format my module. Since what I'm making will be a commercial product, I was wondering what the license is on ShadowTeX?

**Comment by Suthek** [comment]
Hey, sorry for the delay. The project should be used for non-commercial purposes only. The project uses some assets provided to the fanbase by german license holder Pegasus for non-commercial purposes only; and the replication of the style itself is likely a grey area I do not wish to test.
